### PR TITLE
# New wizz Finality Provider

### PR DESCRIPTION
**Pull request by wizz-wallet-dev**
# New wizz Finality Provider

## Checklist

- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey @wizz-wallet-dev the user that should submit the PR is @tyleryu12 as  the PR #132 
Can you verify?

**Comment by RafilxTenfen** [comment]
Hey @wizz-wallet-dev, actually the user to submit the PR should be @tyleryu12

**Comment by tyleryu12** [comment]
I was previously using my personal GitHub account, but we've decided to officially use the team account(wizz-wallet-dev) instead. The PR from the tyleryu12 account has been closed by myself.

**Comment by RafilxTenfen** [comment]
@tyleryu12 thanks for clarifying!

**Review by RafilxTenfen — APPROVED** [review]
:tada:

**Review by vitsalis — APPROVED** [review]

**Pull request merged**
