### PR TITLE
New Validation Cloud Finality Provider

### PR DESCRIPTION
**Pull request by validationcloud-eng**
# New ValidationCloud Finality Provider

## Checklist

- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey @validationcloud-eng, seems like the user `mo-husseini-vc` should submit the PR, can you verify ?

**Comment by mo-husseini-vc** [comment]
Hey @RafilxTenfen. I believe we have used @validationcloud-eng handle in the KYB? Could you please check again? I could submit the PR from my account but would be better if we use @validationcloud-eng.

Thanks!

**Comment by RafilxTenfen** [comment]
@mo-husseini-vc you commenting that approving @validationcloud-eng is good enough ^^

**Review by RafilxTenfen — APPROVED** [review]
:100:

**Comment by mo-husseini-vc** [comment]
> @mo-husseini-vc you commenting that approving @validationcloud-eng is good enough ^^

Awesome! Thank you!

**Review by vitsalis — APPROVED** [review]

**Pull request merged**
