### PR TITLE
New parameters version - Update

### PR DESCRIPTION
**Pull request by KonradStaniec**
Instead of: https://github.com/babylonlabs-io/networks/pull/356

### CODE REVIEW

**Review by vitsalis — APPROVED** [review]

**Review by filippos47 — APPROVED** [review]

**Comment by brianlealt** [comment]
AltLayer params downloaded and applied

**Comment by liewhite** [comment]
CoinSummerLabs params downloaded and applied

**Comment by kwantam** [comment]
Cubist params downloaded and applied.

**Comment by zellic-audit** [comment]
Zellic downloaded and applied

**Comment by ivy191118** [comment]
RockX params downloaded and applied.

**Pull request merged**
