### PR TITLE
New Haris Finality Provider

### PR DESCRIPTION
**Pull request by Mernajop**
# New Haris Finality Provider

## Checklist

- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey, seems like the user Mernajop should be the one to submit the PR, please check

**Comment by har1sssssss** [comment]
Hello @RafilxTenfen - there was a little mismatch after I submit my github for KYC - as I reorginized my github and changed nickname as you can see. As a proof I can give you my PR link from testnet BBN-4 for provider registration and you can see that it's me the one who got the invitation - https://github.com/babylonchain/networks/pull/328

**Comment by RafilxTenfen** [comment]
HEy @har1sssssss you need to use the github account `Mernajop` to submit the PR or update the one set in KYB

**Comment by Mernajop** [comment]
Changed it back to @Mernajop should be good now

**Review by RafilxTenfen — APPROVED** [review]
:tada:

**Review by vitsalis — APPROVED** [review]

**Pull request merged**
