### PR TITLE
Add bitManna Finality Provider

### PR DESCRIPTION
**Pull request by Jason2d2**
# New bitManna Finality Provider

## Checklist

- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Review by RafilxTenfen — APPROVED** [review]
:100:

**Comment by RafilxTenfen** [comment]
Hey @Jason2d2, the user @bitManna should be the one that submits the PR 
Can you verify?

**Comment by Jason2d2** [comment]
I was unable to to fork with @bitManna, and created an Issue. However, @Jason2d2 was able to fork. I managed the PR with @Jason2d2. I also attempted to update the KYB with the @Jason2d2 handle to match the PR.

**Comment by RafilxTenfen** [comment]
Can you comment with @bitManna user approving @Jason2d2 to submit the PR on your behalf?

**Comment by Jason2d2** [comment]
@RafilxTenfen 

@Jason2d2 submitted PR 326  https://github.com/babylonlabs-io/networks/pull/326on behalf of @bitManna due to a GitHub issue which we have submitted a ticket for. 
I have also submitted an issue on Babylon stating the case: https://github.com/babylonlabs-io/networks/issues/324

I have posted a comment as @bitManna to the PR here https://github.com/babylonlabs-io/networks/pull/326#issuecomment-2295015295
Oddly enough, I only see the @bitManna comment showing on the PR, when I view it as @bitManna. There must be some account issue to be corrected by GitHub support.

I have also posted the issue on our website, [www.bitmanna.com](http://www.bitmanna.com/), scroll to the Babylon section.

I have also sent an email to your gmail from the bitManna email.

**Comment by RafilxTenfen** [comment]
can you make the user @bitManna public available?

**Comment by RafilxTenfen** [comment]
Hey @Jason2d2, can you send an email to "operations@babylonlabs.io" explaining your situation

**Comment by Jason2d2** [comment]
> Hey @Jason2d2, can you send an email to "[operations@babylonlabs.io](mailto:operations@babylonlabs.io)" explaining your situation

I just sent the details. Thank you.

**Review by RafilxTenfen — APPROVED** [review]
:tada:

**Review by vitsalis — APPROVED** [review]

**Pull request merged**
