### PR TITLE
New SnowFall Finality Provider

### PR DESCRIPTION
**Pull request by LoulouCrypto**
# New SnowFall  Finality Provider

## Checklist

- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Comment by LoulouCrypto** [comment]
Hello 
I summit this PR 2 days before and not merge 
why it was nor merge

**Comment by RafilxTenfen** [comment]
> Hello I summit this PR 2 days before and not merge why it was not merge

Hey @LoulouCrypto I did not found your finality provider under the KYB review

**Comment by LoulouCrypto** [comment]
Yes it's at summit ;)

**Comment by LoulouCrypto** [comment]
> > Hello I summit this PR 2 days before and not merge why it was not merge
> 
> Hey @LoulouCrypto I did not found your finality provider under the KYB review

look at the original Github it's from [Summit-Group-IT](https://github.com/Summit-Group-IT/Babylon-Main-networks/tree/main) 

We passed KyB process

**Comment by RafilxTenfen** [comment]
@LoulouCrypto why SnowFall as finality provider name, if you are recognized as https://github.com/babylonchain/networks/blob/main/bbn-test-4/finality-providers/registry/SummitNodes.json 
from bbn-test-4?

**Comment by RafilxTenfen** [comment]
Also, the org https://github.com/Summit-Group-IT is approved in KYB, but I cannot see who make part of it
image

Can you make this information public available?

**Comment by LoulouCrypto** [comment]
> @LoulouCrypto why SnowFall as finality provider name, if you are recognized as https://github.com/babylonchain/networks/blob/main/bbn-test-4/finality-providers/registry/SummitNodes.json from bbn-test-4?

Because we want to lunch under a other name 
i ask in discord but i don't have any answer

**Comment by LoulouCrypto** [comment]
> Also, the org https://github.com/Summit-Group-IT is approved in KYB, but I cannot see who make part of it image
> 
> Can you make this information public available?

I ask

**Comment by LoulouCrypto** [comment]
> @LoulouCrypto why SnowFall as finality provider name, if you are recognized as https://github.com/babylonchain/networks/blob/main/bbn-test-4/finality-providers/registry/SummitNodes.json from bbn-test-4?

We chose to change immediately because you announce no change will be available in a first time ....

**Comment by LoulouCrypto** [comment]
@RafilxTenfen I set me as a Public member 
Is it ok for You ?

**Comment by LoulouCrypto** [comment]
> @LoulouCrypto all good, thanks !

Thx

**Comment by LoulouCrypto** [comment]
> @LoulouCrypto all good, thanks !

It will be good to be merge ?

**Review by RafilxTenfen — APPROVED** [review]
:100:

**Review by vitsalis — APPROVED** [review]

**Pull request merged**
