### PR TITLE
New stakeandrelax Finality Provider

### PR DESCRIPTION
**Pull request by StakeandRelax-Validator**
# New stakeandrelax Finality Provider

## Checklist

- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey @StakeandRelax-Validator, please follow this PR template https://github.com/babylonlabs-io/networks/blob/main/.github/PULL_REQUEST_TEMPLATE/new_finality_provider.md

**Comment by StakeandRelax-Validator** [comment]
> Hey @StakeandRelax-Validator, please follow this PR template https://github.com/babylonlabs-io/networks/blob/main/.github/PULL_REQUEST_TEMPLATE/new_finality_provider.md

Fixed

**Comment by RafilxTenfen** [comment]
Can you update the branch with `main`

**Comment by StakeandRelax-Validator** [comment]
should be ok

**Comment by StakeandRelax-Validator** [comment]
> Can you update the branch with `main`

can you confirm that's all ok? Thanks!

**Comment by RafilxTenfen** [comment]
The PR is okay, what is missing is the confirmation from KYB

**Review by RafilxTenfen — APPROVED** [review]
:tada:

**Review by vitsalis — APPROVED** [review]

**Pull request merged**
