### PR TITLE
new parameters version - ABANDONED

### PR DESCRIPTION
**Pull request by KonradStaniec**
New parameters version for cap-2

### CODE REVIEW

**Review by vitsalis — APPROVED** [review]

**Comment by brianlealt** [comment]
AltLayer params downloaded and applied

**Review by filippos47 — APPROVED** [review]

**Comment by whyrulike** [comment]
RockX downloaded and applied

**Comment by dbkbali** [comment]
Informal Staking params downloaded and applied 🚀

**Comment by zellic-audit** [comment]
Zellic downloaded and applied

**Comment by KonradStaniec** [comment]
closing in favour of - https://github.com/babylonlabs-io/networks/pull/357

**Pull request closed without merging**
