### PR TITLE
add Staked finality provider info

### PR DESCRIPTION
**Pull request by nate-staked**
# New Staked Finality Provider

## Checklist

- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Review by ybstaked — COMMENTED** [review]
lgtm

**Comment by RafilxTenfen** [comment]
Can you update the branch with `main`

**Comment by RafilxTenfen** [comment]
Can you update the PR description to this template https://github.com/babylonlabs-io/networks/blob/main/.github/PULL_REQUEST_TEMPLATE/new_finality_provider.md

**Comment by nate-staked** [comment]
ok updated! (and I checked all the boxes)

**Review by RafilxTenfen — APPROVED** [review]
:100:

**Comment by RafilxTenfen** [comment]
Hey @nate-staked the user approved to submit the PR is @staked-nate, can you verify?

**Review by RafilxTenfen — APPROVED** [review]
:100:

**Pull request merged**
