### PR TITLE
New plotei Finality Provider

### PR DESCRIPTION
**Pull request by savchenkoartema**
# New plotei Finality Provider

## Checklist

- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey @pl0tei the github account @savchenkoartema is supposed to submit this pull request, can you verify?

**Comment by pl0tei** [comment]
yo, i used to be @savchenkoartema, but recently changed, is it a problem? i can change it back if its needed

**Comment by RafilxTenfen** [comment]
> yo, i used to be @savchenkoartema, but recently changed, is it a problem? i can change it back if its needed

it needs to be the one set in KYB

**Comment by savchenkoartema** [comment]
I changed it to the one I wrote in KYB - so hope it's okay now 😀

**Review by RafilxTenfen — APPROVED** [review]
:tada:

**Review by filippos47 — APPROVED** [review]

**Pull request merged**
