### PR TITLE
New RockX Finality Provider

### PR DESCRIPTION
**Pull request by AlexRockX**
- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hry @AlexRockX the user calvinzhou-rockx is the one that should submit the PR, can you verify?

**Comment by calvinzhou-rockx** [comment]
Hi @RafilxTenfen , as per email request to operations@babylonlabs.io, RockX's contact email has been updated to shuangdong@rockx.com, and the github account is this @AlexRockX, please let us if any concern or we need to submit any other info, thanks

**Comment by AlexRockX** [comment]
@RafilxTenfen  We have repeatedly contacted the babylon team and this has been confirmed in the communication email ( change of email address， form calvin@rockx to shuangdong@rockx.com )，So I resubmitted the PR。

**Comment by RafilxTenfen** [comment]
Since @calvinzhou-rockx made the statement that the github should be updated I see no issue in merging it as @AlexRockX, thanks!

**Review by RafilxTenfen — APPROVED** [review]
:100:

**Review by vitsalis — APPROVED** [review]

**Comment by AlexRockX** [comment]
RockX params downloaded and applied

**Pull request merged**
