### PR TITLE
New stakefish Finality Provider

### PR DESCRIPTION
**Pull request by wilsonf2pool**
# New stakefish Finality Provider

## Checklist

- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey @wilsonf2pool I have here that an email `wilson@f2pool.com` should submit the PR, can you associate with this acc and make that information public on the profile

**Comment by wilsonf2pool** [comment]
> Hey @wilsonf2pool I have here that an email `wilson@f2pool.com` should submit the PR, can you associate with this acc and make that information public on the profile

Sure, I just make the email address public. Please check.

**Comment by wilsonf2pool** [comment]
@RafilxTenfen

**Comment by RafilxTenfen** [comment]
@wilsonf2pool sounds good, Thanks!

**Review by vitsalis — APPROVED** [review]

**Pull request merged**
