### PR TITLE
New verse2 Finality Provider

### PR DESCRIPTION
**Pull request by lichkingvamvoo**
# New verse2 Finality Provider

## Checklist

- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey @lichkingvamvoo this account is inconsistent with the KYB, can you verify?

**Comment by lichkingvamvoo** [comment]
> Hey @lichkingvamvoo this account is inconsistent with the KYB, can you verify?

Hi @RafilxTenfen !

Can you please check again?
The GitHub username we submitted and our current GitHub account have the same value, and we submitted it this way and received KYB approval.

Could you please check this image?

babylon3

babylon1


cf) We proceeded with KYB under the Entity name ABSOLIT Limited.

**Comment by RafilxTenfen** [comment]
According to what I checked, the KYB defined `aaa` as github account to submit the PR, can you verify this information?

**Comment by RafilxTenfen** [comment]
@lichkingvamvoo Verified on our end, thanks for the patience and helpfulness

**Review by RafilxTenfen — APPROVED** [review]
:tada:

**Review by vitsalis — APPROVED** [review]

**Pull request merged**
