### PR TITLE
New HTX Finality Provider

### PR DESCRIPTION
**Pull request by macrocan**

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey @macrocan, can you follow the [PR template](https://github.com/babylonlabs-io/networks/blob/main/.github/PULL_REQUEST_TEMPLATE/new_finality_provider.md) and check the boxes?

**Comment by RafilxTenfen** [comment]
> Hey @macrocan, can you follow the [PR template](https://github.com/babylonlabs-io/networks/blob/main/.github/PULL_REQUEST_TEMPLATE/new_finality_provider.md) and check the boxes?

Ping on this @macrocan

**Comment by macrocan** [comment]
- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

**Review by RafilxTenfen — APPROVED** [review]
:100:

**Review by vitsalis — APPROVED** [review]

**Pull request merged**
