### PR TITLE
New pSTAKE Finality Provider

### PR DESCRIPTION
**Pull request by mkRuby009**
# New pSTAKE Finality Provider

## Checklist

- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Comment by mkRuby009** [comment]
@RafilxTenfen We have provided the same valid email we have used for bbn-testnet-4 and one we have used for KYB process. Please can you confirm if below warning for email is an issue or not?

```
./bbn-1/finality-providers/scripts/verify-valid-fp.sh pSTAKE
Verifying /home/manasi/all-repos/bbn-1-networks/bbn-1/finality-providers/scripts/../registry/pSTAKE.json
Finality Provider Moniker: pSTAKE
Finality Provider Security Contact: Hello@pstake.finance
Hello@pstake.finance is not a valid email. Check whether you passed a valid finality provider email.
Finality Provider Commission: 0.03
Finality Provider EOTS Public Key: fc8a5b9930c3383e94bd940890e93cfcf95b2571ad50df8063b7011f120b918a
Finality Provider Signature: 15185d0e57ded0006eeb4d3b0fcc5ac38acd266e7c01cec0f684ae4e9899089e5a8e6ebff0c66a2512d961486bbb09b843d8be5f73d591477e5af0ca5b23aefd
Verifying signature with eotsd...
Verification is successful!
```

**Comment by RafilxTenfen** [comment]
Hey @mkRuby009, this warning is incorrect 
I will verify the email regex checker 
I am still waiting for the KYB verification to start the review

**Comment by mkRuby009** [comment]
> Hey @mkRuby009, this warning is incorrect I will verify the email regex checker I am still waiting for the KYB verification to start the review

Hey @RafilxTenfen Thanks for the reply.
Our KYB verification doc has been reviewed. Please review this PR as possible.
Thanks.

**Comment by RafilxTenfen** [comment]
Thanks.
Still waiting for the KYB approval to review 
@mkRuby009

**Comment by RafilxTenfen** [comment]
Hey @mkRuby009, the github account approved to submit the PR is https://github.com/persistenceOne
Which is a team, you are not a member of that team, can you verify? 
image

**Comment by mkRuby009** [comment]
Hey @RafilxTenfen Perhaps, profile visibility issue. I am already member of this irg since 2 years.
Please check now.

image

**Comment by RafilxTenfen** [comment]
@mkRuby009 Thanks!

**Review by RafilxTenfen — APPROVED** [review]
:100:

**Pull request merged**
