### PR TITLE
New fangdarth Finality Provider

### PR DESCRIPTION
**Pull request by panasyukmaksum**
# New fangdarth Finality Provider

## Checklist

- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey, @fangdarth the user @panasyukmaksum should be the one to submit the PR
Can you verify?

**Comment by fangdarth** [comment]
@RafilxTenfen - as I am taking part in different projects, one of a project forced me to change github nickname in order to match my moniker, thats why I changed it from @panasyukmaksum to @fangdarth

**Comment by RafilxTenfen** [comment]
@fangdarth you need to use the github account `panasyukmaksum` to submit the PR or update the account in KYB

**Comment by panasyukmaksum** [comment]
@RafilxTenfen - can you check it out? Now it's @panasyukmaksum as I stated in KYB verification.

**Review by RafilxTenfen — APPROVED** [review]
:100:

**Review by vitsalis — APPROVED** [review]

**Pull request merged**
