### PR TITLE
Add FTPFProvider finality provider.

### PR DESCRIPTION
**Pull request by Denend**
# New FTPFProvider Finality Provider

## Checklist

- [x] I have followed the finality provider information registry
[guide](https://github.com/babylonlabs-io/networks/blob/main/bbn-1/finality-providers/README.md)
- [x] I have backed up my mnemonic
- [x] I have read and agree to the [Babylon Ecosystem Participant License](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-license.pdf) and the [Babylon Ecosystem Participant Agreement](https://docs.babylonlabs.io/assets/files/babylon-ecosystem-participant-agreement.pdf).

> [!CAUTION]
> The loss of the (generated keys + mnemonic) makes the finality provider
useless and unable to provide finality, which would lead to no transition to
later phases of the Babylon network.

### CODE REVIEW

**Comment by Denend** [comment]
gm guys, is everything alright with my Finality Provider?

**Comment by RafilxTenfen** [comment]
@Denend I did not found your KYB registration

**Comment by Denend** [comment]
@RafilxTenfen I am currently in the process of individual verification, hope its fine for you guys

**Comment by Denend** [comment]
> @Denend I am waiting on you KYB approval to review

image
seems like its good now

**Comment by Denend** [comment]
gm, the deadline is coming, if you require more info, please let me know asap

**Review by RafilxTenfen — APPROVED** [review]
:100:

**Comment by Denend** [comment]
gmgm, @vitsalis @filippos47 according to your instructions its 3.5 hours left till the deadline, could you please check out the PR

**Review by vitsalis — APPROVED** [review]

**Pull request merged**
